spring:
  application:
    name: letterfromthesea
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letterfromthesea
    username: root
    password: 10041004
  logging:
    level:
      com.devkduck.letterfromthesea: INFO
  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 49ad98eb10750970f7ec45a4a3751fa5
#            redirect-uri: http://localhost:8080/callback
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - profile_nickname
#              - profile_image
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
